Repository PeopleAndService/BBasPassenger-Android, pull requests merged in 2021-10, with the labels that each got.

#13 #3 [ui/ux] : BBas 앱 스타일가이드 적용
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/font/nanum_square_ac_bold.otf
  app/src/main/res/font/nanum_square_ac_extrabold.otf
  app/src/main/res/font/nanum_square_ac_regular.otf
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/text_styles.xml
  app/src/main/res/values/themes.xml
Labels: status: merge needed, reviewer: yoongyeong, reviewer: jaeseuk

#14 #10 [epic] : Develop BBas Splash Screen
  .gitignore
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/bbaspassenger/LaunchActivity.kt
  app/src/main/res/drawable/layer_splash.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: status: merge needed, reviewer: yoongyeong, reviewer: jaeseuk

#21 #15 Develop Login with Google
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/bbaspassenger/utils/BBasGlobalApplication.kt
  app/src/main/java/com/pns/bbaspassenger/utils/BBasSharedPreference.kt
  app/src/main/java/com/pns/bbaspassenger/utils/SingleEvent.kt
  app/src/main/java/com/pns/bbaspassenger/view/LaunchActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/LoginActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/MainActivity.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout/activity_login.xml
Labels: status: merge needed, reviewer: jaeseuk

#55 #53 [api] : 도시코드 Int형에서 String형으로 변경
  app/src/main/java/com/pns/bbaspassenger/data/model/LocationEnum.kt
  app/src/main/java/com/pns/bbaspassenger/data/model/UpdateUserRequestBody.kt
  app/src/main/java/com/pns/bbaspassenger/data/model/User.kt
  app/src/main/java/com/pns/bbaspassenger/utils/BBasSharedPreference.kt
  app/src/main/java/com/pns/bbaspassenger/view/UserInfoDialog.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/OnBoardViewModel.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/UserInfoViewModel.kt
Labels: status: merge needed, reviewer: jaeseuk

#54 [epic] material component style 재정의
  app/src/main/res/color/state_chip_background.xml
  app/src/main/res/color/state_chip_text.xml
  app/src/main/res/color/state_thumb.xml
  app/src/main/res/color/state_track.xml
  app/src/main/res/layout/dialog_userinfo.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: status: merge needed, reviewer: suho, reviewer: jaeseuk, ui/ux

#58 OnBoard view 수정
  app/src/main/java/com/pns/bbaspassenger/data/model/Queue.kt
  app/src/main/java/com/pns/bbaspassenger/data/model/RouteQueueInfo.kt
  app/src/main/java/com/pns/bbaspassenger/view/OnBoardActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/OnBoardRouteAdapter.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/OnBoardViewModel.kt
  app/src/main/res/layout/activity_on_board.xml
  app/src/main/res/layout/item_route.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: status: merge needed, reviewer: jaeseuk

#73 #71 [feature] : 앱 실행 시 예약정보 받아오는 부분 추가
  app/src/main/java/com/pns/bbaspassenger/view/LaunchActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/LoginActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/OnBoardActivity.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/LaunchViewModel.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/LoginViewModel.kt
Labels: status: merge needed, reviewer: jaeseuk

#90 #68 [epic]: 예약 기능 Dialog 구현
  app/src/main/java/com/pns/bbaspassenger/adapters/BusSelectAdapter.kt
  app/src/main/java/com/pns/bbaspassenger/data/model/CreateQueueRequestBody.kt
  app/src/main/java/com/pns/bbaspassenger/data/source/BBasService.kt
  app/src/main/java/com/pns/bbaspassenger/repository/ReservationRepository.kt
  app/src/main/java/com/pns/bbaspassenger/utils/BBasBindingAdapter.kt
  app/src/main/java/com/pns/bbaspassenger/view/BusSelectDialog.kt
  app/src/main/java/com/pns/bbaspassenger/view/MainActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/OnBoardActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/ReservationActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/ReservationCompleteDialog.kt
  app/src/main/java/com/pns/bbaspassenger/view/ReservationInfoDialog.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/ReservationViewModel.kt
  app/src/main/res/drawable/bg_reservation_dialog_bottom.xml
  app/src/main/res/drawable/bg_reservation_dialog_top.xml
  app/src/main/res/drawable/shape_circle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_reservation.xml
  app/src/main/res/layout/dialog_bus_select.xml
  app/src/main/res/layout/dialog_reservation_complete.xml
  app/src/main/res/layout/dialog_reservation_info.xml
  app/src/main/res/layout/item_rv_bus_select.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: status: merge needed, reviewer: suho, epic

#91 #89 [feature] : BaseActivity 구현
  app/src/main/java/com/pns/bbaspassenger/view/BaseActivity.kt
Labels: feature, reviewer: suho, status: review needed

#94 #80 [feature] : 마이페이지 앱 도움말 페이지
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pns/bbaspassenger/view/HelpActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/MainTutorialFragment.kt
  app/src/main/java/com/pns/bbaspassenger/view/MyPageActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/MyPageTutorialFragment.kt
  app/src/main/java/com/pns/bbaspassenger/view/OnBoardTutorialFragment.kt
  app/src/main/java/com/pns/bbaspassenger/view/ReservationTutorialFragment.kt
  app/src/main/java/com/pns/bbaspassenger/view/TutorialActivity.kt
  app/src/main/res/layout/activity_help.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/fragment_tutorial.xml
  app/src/main/res/raw/mypage1.png
  app/src/main/res/raw/mypage2.png
  app/src/main/res/raw/mypage3.png
  app/src/main/res/raw/onboard1.png
  app/src/main/res/raw/onboard2.png
  app/src/main/res/raw/onboard3.png
  app/src/main/res/raw/onboard4.png
  app/src/main/res/raw/onboard5.png
  app/src/main/res/raw/onboard6.png
  app/src/main/res/raw/reservation1.png
  app/src/main/res/raw/reservation2.png
  app/src/main/res/raw/reservation3.png
  app/src/main/res/raw/reservation4.png
  app/src/main/res/raw/reservation5.png
  app/src/main/res/raw/reservation6.png
  app/src/main/res/raw/search1.png
  app/src/main/res/raw/search2.png
  app/src/main/res/values/strings.xml
Labels: status: merge needed, reviewer: jaeseuk

#95 #93 [feature] : 정류장으로 예약 진입 시 시작으로 설정
  app/src/main/java/com/pns/bbaspassenger/adapters/BusSystemAdapter.kt
  app/src/main/java/com/pns/bbaspassenger/view/MainActivity.kt
  app/src/main/java/com/pns/bbaspassenger/view/ReservationActivity.kt
  app/src/main/java/com/pns/bbaspassenger/viewmodel/ReservationViewModel.kt
Labels: feature, status: merge needed, reviewer: suho, status: review needed
